###

POST http:/localhost:3000/api/moro
content-type: application/json;

{
    "sender": "Atte",
    "message": "testitervehdys"
}

### get new
POST http:/localhost:3000/api/items
### post new
POST http:/localhost:3000/api/items
content-type: application/json;

{
    "name": "Sitruuna"
}
### Get my user info
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJtYXNhMiIsInBhc3N3b3JkIjoiJDJhJDEwJGsyWmtZVm42S2VIWjg3V2VNSEZZY09SSGJSRTA4VUJhVTd0cFhLWWUxTml2MDZQRGVtaHBpIiwiZW1haWwiOiJtYXNhbWFzYW1hc2FAbW9ja2lkYXRhLmZpIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjVUMDk6MDc6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwNDc0NTEyLCJleHAiOjE3NDA1NjA5MTJ9.HTUMTS-vVA6wqJGM27yT9t0l0XtXXTAhPJD4agkbhEk

###
POST http://localhost:5000/api/users
Content-Type: application/json

    {
    "username": "attekangass",
    "password": "salakala",
    "email": "newuserrr@example.com"
  }

### user login
POST http://localhost:5000/api/auth/login
content-type: application/json

{
  "username": "masa2",
  "password": "salakala2"
}
###
POST http://localhost:5000/api/entries
content-type: application/json

{
  "entry_date": "2025-12-12",
  "mood": "good",
  "weight": "85",
  "sleep_hours": "9",
  "notes": "LIFES good"
}

### get me
GET http://localhost:3000/api/users/1

### get user by id
GET http://localhost:3000/api/users/1

### get user by id
GET http://localhost:3000/api/users/

###
GET http://localhost:3000/api/users


### get entry by userid
GET http://localhost:3000/api/entries/2
